### ISSUE TITLE
No feedback on command palette

### ISSUE THREAD

**Issue by leidegre** [httpsterio/vscode-arctic#11]
I like the theme but this is super annoying. There's no feedback on these items, I don't know what is selected or hovering over.

![image](https://user-images.githubusercontent.com/63085/80086436-03787c00-855a-11ea-83af-d7d1c22089c4.png)

![image](https://user-images.githubusercontent.com/63085/80086331-d3c97400-8559-11ea-9c85-68769795eb5e.png)

**Comment by httpsterio** [comment]
Hey, thanks for this! This has apparently broken by a VS Code update, might've been for a while actually. I'll push out an update ASAP :)

**Comment by httpsterio** [comment]
Confirmed, there's new themable tags introduced in an update that changes the behaviour. I'll go through all of the updated elements and scope this.

**Comment by leidegre** [comment]
If it helps, I'll happily send you some money to fix this. Say 50 EUR?

**Comment by httpsterio** [comment]
Hey!

Thanks for the offer, but I'd feel guilty taking your money for just a theme :) I'm happy you're enjoying in though. I had a few personal things to do so I'm sorry it took me a bit longer than I'd wanted, but there's an update now!

Please report back if you're still finding issues. I'm also accepting PR's if you feel something looks off and want to have a go at them yourself :)

Anyways, have a great week!

**Comment by leidegre** [comment]
Good work should be rewarded. I wish there was a simple way to attach a bounty of sorts to GitHub issues. If I had more experience with themes myself, I would have suggested a PR.

Anyway, thanks for taking care of this! Much appreciated!
