### ISSUE TITLE
Sidebar is way more saturated

### ISSUE THREAD

**Issue by MrSkwiggs** [httpsterio/vscode-arctic#8]
Hello,

For some reason my sidebar is really over-saturated and stands out too much for my liking. The previews I saw on the theme page do not reflect my experience. Is there a way I could customize the sidebar saturation myself? 

<img width="1680" alt="screenshot 2019-01-15 at 14 15 02" src="https://user-images.githubusercontent.com/6209874/51182933-081ea100-18d0-11e9-9d64-162833f0a374.png">

After taking a screenshot I realise that somehow my mac display is probably doing some over-saturation. When I drag VSCode to another display the issue is less noticeable... 

Anyhow, any lead on how to alter the sidebar color myself would be appreciated :)

**Comment by httpsterio** [comment]
Hey, thanks for using my theme!

I'm sorry to hear about your issues. As you suspected, I also think that the issue might be with your display color calibration or contrast settings, but luckily there's also a fix in VSCode. 

Overriding the theme settings is fairly simple. If you open the settings JSON or the settings UI from the command palette and make a config for workbench.colorCustomizations and give a color value to activityBar.background then you'll be able to style your sidebar. I've opened up the steps in a bit more detail below.

1. Hit CMD+Shift+P to open up the command palette. 
2. search for "Open Settings JSON"
3. paste the following into the pane on the right side, after the part where it says "workbench.colorTheme": "henna"

```
    "workbench.colorCustomizations": {"activityBar.background": "#YOUR_COLOR_VALUE"}
```

It might throw an error if you're missing a comma in the settings so make sure that it's formatted properly but if you change #YOUR_COLOR_VALUE to a color of your liking and hit save, it should update the sidebar color.

If there's anything else I can help with, please feel free to hit me up!

**Comment by httpsterio** [comment]
Now that you mentioned the issue, I am actually baffled as the issue is not with your display calibrations. I checked the colors, the hex color value for the sidebar should be #e74c3c but for some reason VSCode changes it to #fa3a2f which is a lot brighter as you noticed.

I'll have to investigate this.

**Comment by MrSkwiggs** [comment]
Hey @httpsterio, thanks for the reply and help :) I'll give it a go, thanks 👍
